defaults:
  - config
  - _self_

LR: 0.002
NUM_ENVS: 128
NUM_STEPS: 128 
TOTAL_TIMESTEPS: 1e7
FC_DIM_SIZE: 128
GRU_HIDDEN_DIM: 128
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
ENT_COEF: 0.0
VF_COEF: 0.5
MAX_GRAD_NORM: 0.25
ACTIVATION: relu
OBS_WITH_AGENT_ID: True
MAP_NAME: 2s3z
SEED: 0
ANNEAL_LR: False
overwrite: False
ckpt_freq: 50

# WandB Params
WANDB_MODE: run
ENTITY: ""
PROJECT: waymax_saphne

# DO NOT CHANGE THESE. They will be set automatically in the code.
NUM_ACTORS: -1
MINIBATCH_SIZE: -1
NUM_UPDATES: -1
exp_dir: ""
ckpt_dir: ""

# DO NOT CHANGE THIS.
max_num_objects: 32
